app:
  name: "web_game"
  mode: "dev"
  port: 8081
  version: "v0.1.1"
  start_time: "2024-06-01"
  machine_id: 1
log:
  level: "debug"
  filename: "web_game.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 101.126.76.114
  port: 3306
  user: "root"
  password: "S21070078"
  dbname: "webGame"
  max_open_connections: 200
  max_idle_connections: 10
#redis:
#  host: "8.130.40.129"
#  port: 6379
#  password: "S21070078"
#  db: 0
#  pool_size: 100